USE sakila;
-- List the number of films per category.
SELECT 
    c.name AS category_name, 
    COUNT(f.film_id) AS total_films
FROM 
    film f
INNER JOIN 
    film_category fc ON f.film_id = fc.film_id
INNER JOIN 
    category c ON fc.category_id = c.category_id
GROUP BY 
    c.name;
    
-- Retrieve the store ID, city, and country for each store.
SELECT 
	s.store_id AS store_id,
    c.city AS city_name,
    co.country AS country_name
FROM 
	store s
INNER JOIN 
	address ad ON ad.address_id = s.address_id
INNER JOIN 
	city c ON c.city_id = ad.address_id
INNER JOIN 
	country co ON co.country_id = c.country_id
GROUP BY s.store_id;

-- Calculate the total revenue generated by each store in dollars.
SELECT 
i.store_id,
SUM(p.amount) AS total_revenue
FROM 
	payment AS p 
JOIN rental AS r
	ON p.rental_id = r.rental_id
JOIN inventory AS i 
	ON r.inventory_id = r.inventory_id	
GROUP BY i.store_id;

-- Determine the average running time of films for each category.
SELECT 
    ct.name AS category_name, 
    AVG(f.length) AS running_time_average
FROM 
    film f
LEFT JOIN 
    film_category fc ON f.film_id = fc.film_id
LEFT JOIN 
    category ct ON fc.category_id = ct.category_id
GROUP BY 
    ct.name;

